### ISSUE TITLE
Gen-Plugin for 3rd Party Plugins generates an incorrect entrypoint

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#418]
Gen-Plugin for 3rd Party Plugins generates an incorrect script entrypoint.

When a 3rd party plugin is generated, installed, and the `aac -h` command is run the following error appears:
```
Traceback (most recent call last):
  File "/workspace/AaC/python/venv/bin/aac", line 33, in <module>
    sys.exit(load_entry_point('aac', 'console_scripts', 'aac')())
  File "/workspace/AaC/python/src/aac/cli/execute.py", line 16, in run_cli
    arg_parser, aac_plugin_commands = _setup_arg_parser()
  File "/workspace/AaC/python/src/aac/cli/execute.py", line 47, in _setup_arg_parser
    aac_and_plugin_commands = get_plugin_commands()
  File "/workspace/AaC/python/src/aac/plugins/plugin_manager.py", line 89, in get_plugin_commands
    return list(flatten([plugin.get_commands() for plugin in get_plugins() if plugin.get_commands()]))
  File "/workspace/AaC/python/src/aac/plugins/plugin_manager.py", line 79, in get_plugins
    return get_plugin_manager().hook.get_plugin()
  File "/workspace/AaC/python/src/aac/plugins/plugin_manager.py", line 22, in get_plugin_manager
    plugin_manager.load_setuptools_entrypoints(PLUGIN_PROJECT_NAME)
  File "/workspace/AaC/python/venv/lib/python3.9/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'test_plugin.test_plugin'
```

The expected entrypoint in `setup.py.jinja2` should be:
```python
"aac": ["{{plugin.name}}={{plugin.implementation_name}}"],
```

The pipeline stage to extend can be found here: https://github.com/jondavid-black/AaC/blob/fe9909a43e0bf5ed33426947a5e6198b65fecedd/.github/workflows/python-tests.yml#L56-L61

## AC:
- [x] Gen-Plugin generates 3rd party plugin entrypoints correctly
- [x] Gen-Plugin moves 3rd party plugin yaml files into the generated plugin files
- [ ] The 3rd Party Plugin integration test attempts to run `aac -h` after the 3rd party plugin is installed
  - [ ] The stage must fail before the plugin is fixed
  - [ ] The state passes after the plugin is fixed 
  - [ ] There is a new 3rd party plugin yaml model file that is distinct from any 1st party plugins
  - [ ] The new plugin file command is present in the help output after installation

**Comment by JustAChucklin** [comment]
@Coffee2Bits is there already a test written for this where it can be tested locally or will the changes need to be tested in the GH pipeline? I am making some changes and I am wanting to make sure things are still stable before I commit if it is possible.

**Comment by Coffee2Bits** [comment]
Rolling to Sprint 4.

**Comment by JustAChucklin** [comment]
AC-1, and 2 seem to be met. I am going to reach out to see if the AC-3 is in regards to the pipeline in GH or if it is something to be checked locally.
