### ISSUE TITLE
Imports that reference non-existent files cause python errors

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#586]
AaC doesn't gracefully handle `imports` that reference non-existent files. Bad file imports should be handled gracefully so that the validation system can identify to the user that the path is invalid.

Example error output:
```
 File "/workspace/.pyenv_mirror/user/3.11.1/bin/aac", line 5, in <module>
    from aac.cli.execute import cli
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/cli/execute.py", line 69, in <module>
    active_context = get_active_context()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/lang/active_context_lifecycle_manager.py", line 26, in get_active_context
    ACTIVE_CONTEXT.import_from_file(ACTIVE_CONTEXT_STATE_FILE_NAME)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/lang/language_context.py", line 643, in import_from_file
    self.add_definitions_from_uri(sanitize_filesystem_path(file), definitions)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/lang/language_context.py", line 157, in add_definitions_from_uri
    definitions = [definition for definition in parse(uri) if not names or definition.name in names]
                                                ^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/io/parser/_parse_source.py", line 42, in parse
    return _parse_file(sanitized_source) if is_file else _parse_str(source_uri or DEFAULT_SOURCE_URI, source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/io/parser/_parse_source.py", line 54, in _parse_file
    definition_lists = [_parse_str(file, _read_file_content(file)) for file in _get_files_to_process(arch_file)]
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/io/parser/_parse_source.py", line 235, in _get_files_to_process
    return list(_recurse_imports(arch_file_path, set()))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/io/parser/_parse_source.py", line 224, in _recurse_imports
    existing.update(_recurse_imports(sanitized_path, existing))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/io/parser/_parse_source.py", line 214, in _recurse_imports
    content = _read_file_content(arch_file_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/aac/io/parser/_parse_source.py", line 201, in _read_file_content
    with open(arch_file_path, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '
```

## AC:
- [ ] When the parser tries to import a file that doesn't exist, it should gracefully fail and return a null value.
- [ ] Errant import paths are logged as an error

**Comment by lizzcondrey** [comment]
These are believed to contribute to some of the errors being encountered and that we want to improve with this story.

https://github.com/jondavid-black/AaC/blob/cfb3922e5cfbfa57af8ad7122717c77b81e6bf09/python/src/aac/io/parser/_yaml.py#L77-L86

https://github.com/jondavid-black/AaC/blob/main/python/src/aac/io/constants.py

**Comment by Coffee2Bits** [comment]
The last AC isn't applicable since we already expect 

The following test failures indicate some of the expected failures that are covered up if we catch parser failures in the importing mechanism.
```
======================================================================
FAIL: test_errors_when_parsing_incomplete_model (tests.io_tests.test_parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/AaC/python/tests/io_tests/test_parser.py", line 71, in test_errors_when_parsing_incomplete_model
    self.check_parser_errors(test_yaml.name, "Definition is missing field 'name'", content)
  File "/workspace/AaC/python/tests/io_tests/test_parser.py", line 39, in check_parser_errors
    parse(filespec)
AssertionError: ParserError not raised

======================================================================
FAIL: test_errors_when_parsing_invalid_yaml (tests.io_tests.test_parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/AaC/python/tests/io_tests/test_parser.py", line 66, in test_errors_when_parsing_invalid_yaml
    self.check_parser_errors(test_yaml.name, "invalid YAML")
  File "/workspace/AaC/python/tests/io_tests/test_parser.py", line 39, in check_parser_errors
    parse(filespec)
AssertionError: ParserError not raised

======================================================================
FAIL: test_errors_when_parsing_non_yaml (tests.io_tests.test_parser.TestParser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/AaC/python/tests/io_tests/test_parser.py", line 76, in test_errors_when_parsing_non_yaml
    self.check_parser_errors(test_yaml.name, "not YAML", content)
  File "/workspace/AaC/python/tests/io_tests/test_parser.py", line 39, in check_parser_errors
    parse(filespec)
AssertionError: ParserError not raised
```

We also expect to catch the ParserError in the plugin execution. https://github.com/jondavid-black/AaC/blob/71c6aaedd68e1b825805015f41702521ac2dc8b9/python/src/aac/plugins/plugin_execution.py#L85-L88
