### ISSUE TITLE
Pip install results in unusable aac installation

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#617]
I was about to start working on a new project and realized my local install of aac was out of date.  I first performed a ```pip install --upgrade aac``` but found that resulted in an installation that wouldn't run commands.  So I ran ```pip uninstall aac``` and ```pip install aac``` assuming that a fresh install might solve the problem, but just encountered the same problem.  Below is the command line output from the end of the fresh install followed by running ```aac version``` with the error message.

```
Installing collected packages: aac
Successfully installed aac-0.1.11
PS C:\Users\black\Documents\repos\AaC-BOM> aac version
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\black\AppData\Local\Programs\Python\Python311\Scripts\aac.exe\__main__.py", line 4, in <module>
  File "C:\Users\black\AppData\Local\Programs\Python\Python311\Lib\site-packages\aac\cli\execute.py", line 69, in <module>
    active_context = get_active_context()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\black\AppData\Local\Programs\Python\Python311\Lib\site-packages\aac\lang\active_context_lifecycle_manager.py", line 26, in get_active_context
    ACTIVE_CONTEXT.import_from_file(ACTIVE_CONTEXT_STATE_FILE_NAME)
  File "C:\Users\black\AppData\Local\Programs\Python\Python311\Lib\site-packages\aac\lang\language_context.py", line 637, in import_from_file       
    raise StateFileError(
aac.persistence.state_file_error.StateFileError: Version mismatch: State file written using version 0.1.9; current AaC version 0.1.11
```

**Comment by Coffee2Bits** [comment]
This is an issue with the persistence file. You can address this by deleting the `state.json` file under `C:\Users\black\AppData\Local\Programs\Python\Python311\Lib\site-packages\aac\state.json`.

This is rough around the edges, we're including some persistence improvements in the 0.2 release, and I'll see what we can do to remove this version mismatch headache.

**Comment by jondavid-black** [comment]
I found and deleted the file you mentioned.  Everything works now!

Since we've created other issues to help solve this in the future, I'll close this issue.
